-- Marketplace MVP: ownership delle schede, servizi/prezzi e richieste di rivendicazione.
--
-- PRIMA DI ESEGUIRE: esportare schema e dati del progetto Supabase.
-- Questa migration presume che public.annunci.id sia bigint, come nella configurazione
-- Supabase più comune. Se `annunci.id` è uuid, sostituire BIGINT con UUID nelle due FK.

alter table public.annunci
  add column if not exists stato text,
  add column if not exists email_contatto text,
  add column if not exists sito_web text,
  add column if not exists claimed_at timestamptz,
  add column if not exists updated_at timestamptz default now();

-- Conserva tutti gli annunci esistenti: nessuna riga viene eliminata o nascosta.
update public.annunci
set stato = case when approvato = true then 'pubblicato' else 'in_revisione' end
where stato is null;

alter table public.annunci
  alter column stato set default 'in_revisione',
  alter column stato set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'annunci_stato_valido'
  ) then
    alter table public.annunci
      add constraint annunci_stato_valido
      check (stato in ('bozza', 'in_revisione', 'pubblicato', 'sospeso', 'rifiutato'));
  end if;
end $$;

create table if not exists public.servizi (
  id bigint generated by default as identity primary key,
  annuncio_id bigint not null references public.annunci(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 2 and 140),
  categoria_servizio text,
  prezzo numeric(10,2),
  prezzo_da numeric(10,2),
  prezzo_a numeric(10,2),
  note text,
  attivo boolean not null default true,
  ordinamento integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint servizi_prezzi_non_negativi check (
    (prezzo is null or prezzo >= 0)
    and (prezzo_da is null or prezzo_da >= 0)
    and (prezzo_a is null or prezzo_a >= 0)
    and (prezzo_da is null or prezzo_a is null or prezzo_da <= prezzo_a)
  )
);

create index if not exists servizi_annuncio_ordinamento_idx
  on public.servizi (annuncio_id, attivo, ordinamento);

create table if not exists public.richieste_rivendicazione (
  id bigint generated by default as identity primary key,
  annuncio_id bigint not null references public.annunci(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  messaggio text,
  stato text not null default 'in_attesa'
    check (stato in ('in_attesa', 'approvata', 'rifiutata')),
  nota_revisione text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (annuncio_id, user_id)
);

create index if not exists richieste_rivendicazione_stato_idx
  on public.richieste_rivendicazione (stato, created_at desc);

alter table public.servizi enable row level security;
alter table public.richieste_rivendicazione enable row level security;

-- Pubblico: vede soltanto i servizi attivi delle schede pubblicate.
drop policy if exists "Servizi pubblici delle schede pubblicate" on public.servizi;
create policy "Servizi pubblici delle schede pubblicate"
  on public.servizi for select
  using (
    attivo = true and exists (
      select 1 from public.annunci a
      where a.id = servizi.annuncio_id
        and a.approvato = true
        and a.stato = 'pubblicato'
    )
  );

-- Proprietario: può leggere e gestire i servizi della propria scheda.
drop policy if exists "Proprietario gestisce i propri servizi" on public.servizi;
create policy "Proprietario gestisce i propri servizi"
  on public.servizi for all to authenticated
  using (exists (select 1 from public.annunci a where a.id = servizi.annuncio_id and a.user_id = auth.uid()))
  with check (exists (select 1 from public.annunci a where a.id = servizi.annuncio_id and a.user_id = auth.uid()));

-- Un professionista può creare e consultare solo le proprie richieste.
drop policy if exists "Utente crea le proprie richieste di rivendicazione" on public.richieste_rivendicazione;
create policy "Utente crea le proprie richieste di rivendicazione"
  on public.richieste_rivendicazione for insert to authenticated
  with check (user_id = auth.uid() and stato = 'in_attesa');

drop policy if exists "Utente legge le proprie richieste di rivendicazione" on public.richieste_rivendicazione;
create policy "Utente legge le proprie richieste di rivendicazione"
  on public.richieste_rivendicazione for select to authenticated
  using (user_id = auth.uid());

-- Approvazione manuale iniziale:
-- 1. verificare la richiesta nel dashboard Supabase;
-- 2. aggiornare annunci.user_id e annunci.claimed_at;
-- 3. impostare richieste_rivendicazione.stato = 'approvata' e reviewed_at = now().
-- Il service role e SQL Editor bypassano RLS; non esporre mai il service role nel frontend.

